#bodyContent {
	FONT-SIZE: 114%
}
H2 {
	FONT-WEIGHT: bold; FONT-SIZE: 148%
}
.ns--2  #content {
	BACKGROUND: #fffff6
}
.ns--2  #p-cactions LI A {
	BACKGROUND: #fffff6
}
.ns--1  #content {
	BACKGROUND: #fffff6
}
.ns--1  #p-cactions LI A {
	BACKGROUND: #fffff6
}
.ns-2  #content {
	BACKGROUND: #fffff6
}
.ns-2  #p-cactions LI A {
	BACKGROUND: #fffff6
}
.ns-3  #content {
	BACKGROUND: #fffff6
}
.ns-3  #p-cactions LI A {
	BACKGROUND: #fffff6
}
.ns-4  #content {
	BACKGROUND: #fffff6
}
.ns-4  #p-cactions LI A {
	BACKGROUND: #fffff6
}
.ns-5  #content {
	BACKGROUND: #fffff6
}
.ns-5  #p-cactions LI A {
	BACKGROUND: #fffff6
}
.ns-6  #content {
	BACKGROUND: #fffff6
}
.ns-6  #p-cactions LI A {
	BACKGROUND: #fffff6
}
.ns-7  #content {
	BACKGROUND: #fffff6
}
.ns-7  #p-cactions LI A {
	BACKGROUND: #fffff6
}
.ns-8  #content {
	BACKGROUND: #fffff6
}
.ns-8  #p-cactions LI A {
	BACKGROUND: #fffff6
}
.ns-9  #content {
	BACKGROUND: #fffff6
}
.ns-9  #p-cactions LI A {
	BACKGROUND: #fffff6
}
.ns-10  #content {
	BACKGROUND: #fffff6
}
.ns-10  #p-cactions LI A {
	BACKGROUND: #fffff6
}
.ns-11  #content {
	BACKGROUND: #fffff6
}
.ns-11  #p-cactions LI A {
	BACKGROUND: #fffff6
}
.ns-12  #content {
	BACKGROUND: #fffff6
}
.ns-12  #p-cactions LI A {
	BACKGROUND: #fffff6
}
.ns-13  #content {
	BACKGROUND: #fffff6
}
.ns-13  #p-cactions LI A {
	BACKGROUND: #fffff6
}
.ns-14  #content {
	BACKGROUND: #fffff6
}
.ns-14  #p-cactions LI A {
	BACKGROUND: #fffff6
}
.ns-15  #content {
	BACKGROUND: #fffff6
}
.ns-15  #p-cactions LI A {
	BACKGROUND: #fffff6
}
